apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
  labels:
    app: budzetownik
    tier: frontend
spec:
  type: NodePort
  selector:
    app: budzetownik
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  externalTrafficPolicy: Cluster
