apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-front-sa
  namespace: ecommerce-dev
  labels:
    app: front
    comp-type: frontend

automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-back-sa
  namespace: ecommerce-dev
  labels:
    app: back
    comp-type: backend

automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-db-sa
  namespace: ecommerce-dev
  labels:
    app: db
    comp-type: database

automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-front-sa
  namespace: ecommerce-prod
  labels:
    app: front
    comp-type: frontend

automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-back-sa
  namespace: ecommerce-prod
  labels:
    app: back
    comp-type: backend

automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-db-sa
  namespace: ecommerce-prod
  labels:
    app: db
    comp-type: database

automountServiceAccountToken: true

