app:
  name: test-nginx
  annotations: this is a dev nginx deployment
  version: 1.0.1


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
replicaCount: 3

annotations: []

podLabels:
  environment: prod

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable" # changed to stable from latest on prod
  containerPort: 80


service:
  type: ClusterIP
  port: 8080
  targetPort: 80

ingress:
  enabled: true # true in prod
  host: test-nginx.local
  path: /

config: 
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 'That is a prod configmap.!\n';
        }
      }
    }

secrets:
  useless-secret-thing: "cringest_password_thats_ever_lived"

resources:
  requests:
    memory: "100Mi"
    cpu: "200m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /
    port: 80

  initialDelaySeconds: 2
  periodSeconds: 5
  failureThreshold: 3            
  successThreshold: 1   

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 30


volumes:
  - name: dev-mount-config
  

volumeMounts:
  - name: dev-mount-config
    mountPath: /etc/nginx/nginx.conf
    subPath: nginx.conf
    readOnly: true
