app:
  name: webapp
  version: 1.0.0

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

config:
  ENVIRONMENT: "default"
  LOG_LEVEL: "INFO"
  CACHE_TTL: "3600"

secrets:
  DATABASE_PASSWORD: "secret123"
  API_KEY: "sk-1234567890"
