apiVersion: apps/v1
kind: Deployment
metadata:
  name: krai-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: krai-frontend
  template:
    metadata:
      labels:
        app: krai-frontend
    spec:
      containers:
        - name: krai-frontend
          image: krai-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: krai-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort
