apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}
