{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-nginx-chart.fullname" . }}-configmap
  labels:
    {{- include "test-nginx-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}