apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2025-08-27T21:56:05Z"
  generation: 7
  labels:
    app: backend
  name: backend
  namespace: default
  resourceVersion: "23981"
  uid: 963298b1-70c5-4c6c-9360-f752fc9fbd6c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-28T08:28:00-04:00"
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: backend:latest
        imagePullPolicy: IfNotPresent
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-28T12:27:56Z"
    lastUpdateTime: "2025-08-28T12:27:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-27T21:56:05Z"
    lastUpdateTime: "2025-08-28T12:28:01Z"
    message: ReplicaSet "backend-7c64bc55d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
