apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"frontend"},"type":"NodePort"}}
  creationTimestamp: "2025-08-27T16:16:22Z"
  labels:
    app: frontend
  name: frontend-service
  namespace: default
  resourceVersion: "12589"
  uid: 1a031f81-b778-4c0c-94e6-e61329ec850c
spec:
  clusterIP: 10.107.111.228
  clusterIPs:
  - 10.107.111.228
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32503
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
