apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mysql","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mysql"}},"template":{"metadata":{"labels":{"app":"mysql"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"rootpass"},{"name":"MYSQL_DATABASE","value":"appdb"},{"name":"MYSQL_USER","value":"app"},{"name":"MYSQL_PASSWORD","value":"apppass"}],"image":"mysql:8","name":"mysql","ports":[{"containerPort":3306}],"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mysqldata"}]}],"volumes":[{"name":"mysqldata","persistentVolumeClaim":{"claimName":"mysql-data"}}]}}}}
  creationTimestamp: "2025-08-27T16:31:42Z"
  generation: 7
  name: mysql
  namespace: default
  resourceVersion: "23846"
  uid: 2db5ef6c-dff2-4878-84ad-52e3963ee440
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-27T16:08:11-04:00"
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: appdb
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
          value: apppass
        image: mysql:8
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-27T16:31:42Z"
    lastUpdateTime: "2025-08-27T20:08:13Z"
    message: ReplicaSet "mysql-58756c9f59" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-08-28T12:27:06Z"
    lastUpdateTime: "2025-08-28T12:27:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
