apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ecommerce-dev
  labels:
    app: frontend
    component: ui
    environment: dev
  annotations:
    description: "Service account dla frontendu dev ver"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ecommerce-dev
  labels:
    app: backend
    component: api
    environment: dev
  annotations:
    description: "Service account dla backend REST API dev ver"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: ecommerce-dev
  labels:
    app: database
    component: storage
    environment: dev
  annotations:
    description: "Service account dla PostgreSQL bd dev ver"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ecommerce-prod
  labels:
    app: frontend
    component: ui
    environment: prod
  annotations:
    description: "Service account dla frontend prod ver"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ecommerce-prod
  labels:
    app: backend
    component: api
    environment: prod
  annotations:
    description: "Service account dla backend prode ver"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: ecommerce-prod
  labels:
    app: database
    component: storage
    environment: prod
  annotations:
    description: "Service account dla PostgreSQL prod ver"
automountServiceAccountToken: false
