apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  APP_MODE: "production"
  LOG_LEVEL: "info"
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque  # Poprawka 1: Zmiana typu na Opaque
data:
  # Wartości powinny być zakodowane w base64, for security :)
  DB_USERNAME: YWRtaW4=  # admin
  DB_PASSWORD: U3VwZXJTZWNyZXQxMjM=  # SuperSecret123
  API_KEY: c2stMTIzNDU2Nzg5MGFiY2RlZg==  # sk-1234567890abcdef

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:latest
        ports:
        - containerPort: 80    
        # Zmiana env na envFrom
        envFrom:
        - configMapRef:
            name: webapp-config
        - secretRef:
            name: webapp-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true  # Secret tylko read-only!!!
        
        startupProbe:
          httpGet:  # Zmiana exec na httpGet
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30

      volumes:
      - name: config-volume
        configMap:
          name: webapp-config
      - name: secret-volume
        secret:
          secretName: webapp-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp  # Wszędzie używamy webapp, nie myapp
  ports:
  - port: 80        
    targetPort: 80      
    nodePort: 31377 # 8000 było poza zakresem NodePort 30000-32767
  type: NodePort