apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: back
    tier: backend
  namespace: testapp
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: back
    tier: backend