apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: testapp
  labels:
    app: back
    tier: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10 
  selector:
    matchLabels:
      app: back
      tier: backend
  template:
    metadata:
      labels:
        app: back
        tier: backend
    spec:
      containers:
      - name: back
        image: back:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: back
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        
