apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: testapp
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpasswd
        - name: MYSQL_DATABASE
          value: testappDB
        - name: MYSQL_USER
          value: testapp
        - name: MYSQL_PASSWORD
          value: testapppasswd
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc