apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: testapp
  labels:
    app: front
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10 
  selector:
    matchLabels:
      app: front
      tier: frontend
  template:
    metadata:
      labels:
        app: front
        tier: frontend
    spec:
      containers:
      - name: front
        image: front:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: front
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        
