apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front
    tier: frontend
  namespace: testapp
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: front
    tier: frontend