apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  labels:
    environment: production
    app: nginx
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: production
      app: nginx
  template:
    metadata:
      labels:
        environment: production
        app: nginx
        tier: frontend
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80