# ServiceAccounts in ecommerce-dev
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ecommerce-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ecommerce-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: ecommerce-dev

# ServiceAccounts in ecommerce-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ecommerce-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ecommerce-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: ecommerce-prod